<?php

// competitor thread
$CompetitorParam=array(
	1=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	2=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	3=>array(
        "CatchHtmlMaxThread"=>25,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true,
	),
	4=>array(
        "CatchHtmlMaxThread"=>25,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	5=>array(
        "CatchHtmlMaxThread"=>25,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	6=>array(
        "CatchHtmlMaxThread"=>25,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	7=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	8=>array(
        "CatchHtmlMaxThread"=>15,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>15,
        "CatchTempCSGOURLMaxThread"=>15,
        "IsCatchGo"=>true
	),
	9=>array(
        "CatchHtmlMaxThread"=>25,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>false
	),
	10=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	11=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        'CatchCodeMaxThread'=>5,
        "CatchTempCSGOMaxThread"=>20,
        "CatchTempCSGOURLMaxThread"=>20,
        "IsCatchGo"=>true
	),
	12=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>20,
        "CatchTempCSGOURLMaxThread"=>20,
        "IsCatchGo"=>true
	),
	13=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	14=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>20,
		"CatchTempCSGOURLMaxThread"=>20,
		"IsCatchGo"=>true
	),
	15=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	16=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	17=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	18=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	19=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	20=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	21=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
	),
	22=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	23=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	24=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	25=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	26=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	27=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	28=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	29=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
	30=>array(
		"CatchHtmlMaxThread"=>10,
		"CatchGOMaxThread"=>5,
		"CatchTempCSGOMaxThread"=>5,
		"CatchTempCSGOURLMaxThread"=>5,
		"IsCatchGo"=>true
	),
    31=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    32=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    33=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    34=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    35=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    36=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    37=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    38=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    39=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    40=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    41=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    42=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    43=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    44=>array(
        "CatchHtmlMaxThread"=>10,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    45=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    46=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    47=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    48=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    49=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    50=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    51=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    52=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    53=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    54=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    55=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    56=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    57=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    58=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    59=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    60=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    61=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    ),
    62=>array(
        "CatchHtmlMaxThread"=>5,
        "CatchGOMaxThread"=>5,
        "CatchTempCSGOMaxThread"=>5,
        "CatchTempCSGOURLMaxThread"=>5,
        "IsCatchGo"=>true
    )
);
		

//dir
define("DIR_IP_CONFIG",INCLUDE_ROOT."data/");
define("DIR_CATCH_HTML",INCLUDE_ROOT."catch_html/");
define("DIR_TMP_COOKIE",INCLUDE_ROOT."tmp/");

//file
define("LOG_RESOLVE_FILE",INCLUDE_ROOT."log/resolve_log.txt");
define("LOG_RESOLVE_CATE_FILE",INCLUDE_ROOT."log/resolve_cate_log.txt");
define("LOG_OUT_FILE",INCLUDE_ROOT."log/thread_out_log.txt");
define("LOG_NEW_STORE_BASE_INFO_FILE",INCLUDE_ROOT."log/get_new_store_base_info.txt"); //获取新商家时log
define("LOG_LANDING_FILE",INCLUDE_ROOT."log/landing_log.txt");	//landing匹配页面

//param
define("PARAM_SERVER","_188");
define("PARAM_MAX_ACTIVE_IPS",20);
define("PARAM_CATCH_FAIL_MAX_COUNT_IP",5); //IP抓取失败最大次数
define("COMPETITOR_INFO_KEY","COMPETITOR_INFO_KEY"); //竞争对手数据缓存KEY

//运行设备唯一名称
define("MERCHANT_NAME","QCLOUD_ROBOT");
